import { EventItem } from '../types';

export const DEFAULT_EVENTS: EventItem[] = [
  {
    id: 'evt-bgmi',
    name: 'E-SPORTS — BGMI',
    slug: 'bgmi',
    description: 'Compete in an exciting BGMI tournament and showcase your gaming skills, teamwork and strategy.',
    category: 'ESPORTS',
    day: 'DAY_1',
    date: '14 September 2026',
    startTime: '10:00 AM',
    endTime: '01:00 PM',
    venue: 'Apex University Auditorium, VT Road, Mansarovar',
    registrationFee: 49,
    maxParticipants: 100,
    isRegistrationOpen: true,
    requiresPayment: true,
    rules: '1. Squad registration (1-4 players).\n2. BGMI mobile only (emulators strictly prohibited).\n3. Match room ID and password shared 15 mins prior.\n4. Decisions of tournament admins are final.',
    isTeamEvent: true,
    minTeamSize: 1,
    maxTeamSize: 4,

  },
  {
    id: 'evt-free-fire',
    name: 'E-SPORTS — FREE FIRE',
    slug: 'free-fire',
    description: 'Battle it out in a competitive Free Fire tournament and prove your gaming skills.',
    category: 'ESPORTS',
    day: 'DAY_1',
    date: '14 September 2026',
    startTime: '02:00 PM',
    endTime: '05:00 PM',
    venue: 'Apex University Auditorium, VT Road, Mansarovar',
    registrationFee: 49,
    maxParticipants: 100,
    isRegistrationOpen: true,
    requiresPayment: true,
    rules: '1. Squad registration (1-4 players).\n2. Mobile devices only.\n3. Room credentials shared 15 minutes before match start.\n4. Fair play policy enforced.',
    isTeamEvent: true,
    minTeamSize: 1,
    maxTeamSize: 4,

  },
  {
    id: 'evt-blind-coding',
    name: 'BLIND CODING COMPETITION',
    slug: 'blind-coding',
    description: 'Test your programming logic and problem-solving skills with screens turned off.',
    category: 'TECHNICAL',
    day: 'DAY_1',
    date: '14 September 2026',
    startTime: '11:00 AM',
    endTime: '01:00 PM',
    venue: 'Apex University Auditorium, VT Road, Mansarovar',
    registrationFee: 49,
    maxParticipants: 60,
    isRegistrationOpen: true,
    requiresPayment: true,
    rules: '1. Individual participation.\n2. Monitors will be turned off while typing code.\n3. 3 rounds of escalating algorithmic difficulty.\n4. Syntax errors and execution time dictate score.',
    isTeamEvent: false,
    minTeamSize: 1,
    maxTeamSize: 1,

  },
  {
    id: 'evt-quiz',
    name: 'QUIZ COMPETITION',
    slug: 'quiz',
    description: 'Test your knowledge across engineering, technology, science, general awareness and current affairs.',
    category: 'TECHNICAL',
    day: 'DAY_1',
    date: '14 September 2026',
    startTime: '02:30 PM',
    endTime: '04:30 PM',
    venue: 'Apex University Auditorium, VT Road, Mansarovar',
    registrationFee: 49,
    maxParticipants: 80,
    isRegistrationOpen: true,
    requiresPayment: true,
    rules: '1. Written buzzer and rapid-fire rounds.\n2. Covers core engineering, tech history, and current innovations.\n3. Negative marking in final rounds.',
    isTeamEvent: false,
    minTeamSize: 1,
    maxTeamSize: 1,

  },
  {
    id: 'evt-cultural',
    name: 'CULTURAL PERFORMANCE',
    slug: 'cultural-performance',
    description: 'A platform for students to showcase their singing, dancing, performing and creative talents.',
    category: 'CULTURAL',
    day: 'DAY_2',
    date: '15 September 2026',
    startTime: '10:00 AM',
    endTime: '01:30 PM',
    venue: 'Apex University Auditorium, VT Road, Mansarovar',
    registrationFee: 0,
    maxParticipants: 150,
    isRegistrationOpen: true,
    requiresPayment: false,
    rules: '1. Solo or group performance allowed.\n2. Time limit: Maximum 4 minutes per act.\n3. Audio tracks must be submitted to coordinators in advance.',
    isTeamEvent: false,
    minTeamSize: 1,
    maxTeamSize: 6,

  },
  {
    id: 'evt-prize',
    name: 'PRIZE DISTRIBUTION',
    slug: 'prize-distribution',
    description: "Recognizing winners and celebrating excellence achieved during Engineer's Day 2026.",
    category: 'CEREMONY',
    day: 'DAY_2',
    date: '15 September 2026',
    startTime: '03:00 PM',
    endTime: '05:30 PM',
    venue: 'Apex University Auditorium, VT Road, Mansarovar',
    registrationFee: 0,
    maxParticipants: null,
    isRegistrationOpen: false,
    requiresPayment: false,
    rules: '1. Open to all students, faculty, and participants.\n2. Trophy, medal, and certificate distribution for event winners.',
    isTeamEvent: false,
    minTeamSize: 1,
    maxTeamSize: 1,

  },
];
